spring:
  datasource:
    url: jdbc:h2:mem:testdb
    datasource:
      username: sa
      password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      console:
        path: /h2-console

